# Generated by Django 3.1.7 on 2021-02-20 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210220_0635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
