# Generated by Django 3.1.7 on 2021-03-02 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20210301_0637'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='picture',
            field=models.BinaryField(editable=True, null=True),
        ),
    ]
