# Generated by Django 3.1.7 on 2021-03-03 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20210303_0415'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='sale_presentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
