# Generated by Django 3.1.7 on 2021-03-04 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_variation_sale_presentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variation',
            name='sale_presentage',
        ),
    ]
